### ISSUE TITLE
Exception on scene load

### ISSUE THREAD

**Issue by Halbann** [LGhassen/Deferred#1]
https://github.com/LGhassen/Deferred/blob/1557c64ab0c9e304254758a95f087fdf6aca699e/DeferredKSP/Deferred.cs#L262

![image](https://github.com/LGhassen/Deferred/assets/30965946/3eea26cb-7f90-499d-b0a1-ae4bd163c9d5)

**Comment by LGhassen** [comment]
Is this with a debugger connected or something?

**Comment by LGhassen** [comment]
fixed

**Comment by Halbann** [comment]
> Is this with a debugger connected or something?

@LGhassen I'm running the game with the Unity player in debug mode for modding. Bit of an aside but Scatterer actually doesn't work while Unity is in debug mode, which is exceedingly rare for a mod. Could be worth looking into. Let me know if you'd like me to make some logs.

https://gist.github.com/gotmachine/d973adcb9ae413386291170fa346d043

**Comment by LGhassen** [comment]
Yeah I never tried that. Feel free to make a PR if you want to look into it, otherwise I have other priorities right now.
