### ISSUE TITLE
Certain modded part's 'Line drawers' cant' draw lines 

### ISSUE THREAD

**Issue by Hyenadae** [LGhassen/Deferred#13]
I'm using the DMagic Orbital Science mod, and I'm seeing one part (asteroid scanner) cannot draw itself properly. Seemingly turned the line or cone into a simple pink rectangle, oopsie!

![image](https://github.com/LGhassen/Deferred/assets/3067205/f35338f3-f3b2-48c4-939e-7cec7a8eb90a)

Using latest (v1.10) deferred renderer with latest Scatterer, SMAA only (TAA's blur and destruction of the stars/space in orbit is too distracting. Dunno if you could ever rig in DLSS2/FSR2 with the depth data you get?)

Seemingly gets occluded properly by deferred rendering, but only in debug

![image](https://github.com/LGhassen/Deferred/assets/3067205/89b0442f-3846-4923-af8e-09db14b88c07)

![image](https://github.com/LGhassen/Deferred/assets/3067205/42603edd-0a93-494a-8c91-8a0d6c5ad5c2)

**Comment by LGhassen** [comment]
> Using latest (v1.10) deferred renderer with latest Scatterer, SMAA only (TAA's blur and destruction of the stars/space in orbit is too distracting. Dunno if you could ever rig in DLSS2/FSR2 with the depth data you get?)

This is unrelated to deferred and that's not a project I'm gonna get into right now, and depth isn't enough

> Seemingly gets occluded properly by deferred rendering, but only in debug

What exactly do you mean? What gets occluded and what's correctly?

**Comment by Hyenadae** [comment]
Ah, well apparently this mod wasn't the issue. Honestly not surprised because it's been really good so far. My DMagic files were for a KSP 1.4 (from 2018...). I've never seen it give me a visual bug before, so whatever KSP did between 1.4 to 1.8 with rendering uh, well broke the lines apparently.

![image](https://github.com/LGhassen/Deferred/assets/3067205/63f01ff4-bdaa-49c7-8f2c-a3b46f541323)

Sorry for wasting your time! I can't wait for Parallax folks to update for the "full suite" of visual overhauls. Seeing lots of this mod on social media :)

**Comment by LGhassen** [comment]
Thank you for the update
