### ISSUE TITLE
Installing fixed individual DLLs for Scattrer and Voumetric clouds breaks them

### ISSUE THREAD

**Issue by BobKermanIndustries** [LGhassen/Deferred#15]
Installing the fixed individual DLLs for Scatter and Volumetric clouds breaks them. Not installing the fixed DLLs renders the clouds and atmosphere, but I am unsure if that is with forward or something else. Log attached.
[KSP.log](https://github.com/user-attachments/files/16047034/KSP.log)

**Comment by LGhassen** [comment]
Was it you who left the comment on Patreon also or someone else? In any case send me a message on Patreon, I'll send you the latest version there and it'll be easier to debug.
