### ISSUE TITLE
Dark side of moons/planets is not (completely) dark

### ISSUE THREAD

**Issue by Zeldrine** [LGhassen/Deferred#19]
Hey (thanks for the amazing work):

After installing Deffered Lightning, I had this bug appear where dark side of planets and moons terrains would not be completely dark anymore (see pictures). 
I have the impression that there is a "distance" between the craft and the body where some lightning effect would apply because the area is bigger when the altitude is lower (Duna : small surface of terrain being lit / Mun : larger area).
Related to that, the craft will always be visible, even in pitch black.

When installing DL, I also had to manually update Kopernicus, Textures Unlimited and Parallax so I'm also looking there also I find it less likely the problem is coming from there.

Any ideas?
Best regards

[KSP.log](https://github.com/user-attachments/files/16053106/KSP.log)

![KSP DL Bug - Eve](https://github.com/LGhassen/Deferred/assets/83477717/3b6b9e0d-a16e-48b5-9786-30f513c5d331)
![KSP DL Bug - Duna](https://github.com/LGhassen/Deferred/assets/83477717/bf55bd70-f913-46d5-9286-1418662cca47)
![KSP DL Bug - Mun](https://github.com/LGhassen/Deferred/assets/83477717/12de8cc7-fd08-4e27-86e5-0b2b18fef63e)
![KSP DL bug - Eeloo](https://github.com/LGhassen/Deferred/assets/83477717/bfd16799-1a68-44a9-a116-59d8f18e220b)

**Comment by LGhassen** [comment]
This was always the case, there is always a faint ambient for gameplay reasons.

**Comment by Zeldrine** [comment]
Hi again (thank you for your quick response),

Ok so my apologies, you were right about the fact that it's not supposed to be pitch black.

However there is still a problem: The pitch black that's outside the visible terrain.
This is mostly visible on the 2nd screenshot, where only a small part of the body's terrain is visible,
But it's also visible on 3rd and 4th screenshots, where the pitch black part is visible on the edge of the visible terrain.

I made a comparaison without DL : 

Duna without DL : 
![KSP DL NoBug - Duna](https://github.com/LGhassen/Deferred/assets/83477717/06888446-4420-4078-a225-5e6f51ace7c5)

Duna with DL : 
![KSP DL Bug - Duna](https://github.com/LGhassen/Deferred/assets/83477717/b0473e37-cf52-4415-a761-a2a9b0b98871)

Mun without DL : 
![KSP DL NoBug - Mun](https://github.com/LGhassen/Deferred/assets/83477717/3697540c-f533-4d2a-b5b3-8194146a84cf)

Mun with DL : 
![KSP DL Bug - Mun](https://github.com/LGhassen/Deferred/assets/83477717/3a3c843a-12cb-4010-a0d8-4044944288df)

Thank you for your help :) !
