### ISSUE TITLE
Half the terrain looks darker 

### ISSUE THREAD

**Issue by cagataysunal** [LGhassen/Deferred#2]
On kerbin (so far, haven't tested it on other bodies), half of the terrain looks darker. This seems to be affected by camera position, so if I zoom out or zoom in, or pan / rotate the camera, the effect also changes accordingly. 

System Specs:
* OS: Ubuntu 22.04.4
* GPU: RTX 3070
* Resolution: 3840x2160
* RAM: 64 GB
* CPU: Ryzen 5 5600x

The game is native linux version.

Here are screenshots:
![Ekran Görüntüsü - 2024-06-22 14-30-44](https://github.com/LGhassen/Deferred/assets/32794704/920026b2-4fcf-4436-b43d-98478b0c2722)

![Ekran Görüntüsü - 2024-06-22 14-31-01](https://github.com/LGhassen/Deferred/assets/32794704/3988b7f0-ed15-426b-bbf9-9b1fd775c35f)

![Ekran Görüntüsü - 2024-06-22 14-34-44](https://github.com/LGhassen/Deferred/assets/32794704/a8bc9c09-3c62-42ba-99a9-f432c9f04775)

The only mods installed are Scatterer, EVE (Volumetric Clouds) and Deferred, along with their dependencies.

**Comment by LGhassen** [comment]
Thanks a lot for the report, I can reproduce the issue on OpenGL on windows, investigating...

**Comment by LGhassen** [comment]
Should be fixed now, try the newest release.

On a sidenote, consider running your game through proton to have better performance and better compatibility with visual mods, as the native OpenGL version runs worse in many ways.
