### ISSUE TITLE
Dark side of moons/planets is partially dark

### ISSUE THREAD

**Issue by Zeldrine** [LGhassen/Deferred#20]
(Follow-up to #19)

Hi again (thank you for your quick response),

Ok so my apologies, you were right about the fact that it's not supposed to be pitch black.

However there is still a problem: The pitch black that's outside the visible terrain.
This is mostly visible on the 2nd screenshot, where only a small part of the body's terrain is visible,
But it's also visible on 3rd and 4th screenshots, where the pitch black part is visible on the edge of the visible terrain.

I made a comparaison without DL :

Duna without DL :
![KSP DL NoBug - Duna](https://github.com/LGhassen/Deferred/assets/83477717/3d24467a-c83c-4b66-95d4-6f450a145899)

Duna with DL :
![KSP DL Bug - Duna](https://github.com/LGhassen/Deferred/assets/83477717/58019fca-d76a-4860-821a-d3c10db350c1)

Mun without DL :
![KSP DL NoBug - Mun](https://github.com/LGhassen/Deferred/assets/83477717/21d4d9f7-4ad6-4af5-b5c0-437e6edb1525)

Mun with DL :
![KSP DL Bug - Mun](https://github.com/LGhassen/Deferred/assets/83477717/e9e2e719-d81d-484c-b430-a833247e0c1b)

Thank you for your help :) !

**Comment by LGhassen** [comment]
I honestly can't see anything in any of these images unless I take them in photoshop and brighten them up 900%, unless this is a more visible problem it's not worth looking into for me at this point in development.

**Comment by Zeldrine** [comment]
I'll provide a video asap, it's a very visible problem but I'm sorry I couldn't better describe it to you.
The Duna screenshot I provided has this problem where a huge majority of the body's surface is pitch black.

Let me come back to you with a video, and thank you very much for your time! :)

**Comment by Zeldrine** [comment]
I used Duna as it's the most visible example I have: 
https://youtu.be/JKBJNSC2qFg?si=KTRlXJ4XyDsSHXbh

I checked without DL, it wasn't happening

**Comment by LGhassen** [comment]
Have you updated Parallax and Deferred to the last versions from a few days ago?

**Comment by Zeldrine** [comment]
"Have you updated Parallax and Deferred to the last versions from a few days ago?" > I had yes, followed the instructions precisely  for each mods.

In the end, I re-installed everything (EVE ; Parallax ; Deffered ; Kopernicus ; Scatterer) and the problem desappeard :)

Thank you very much for you support <3
