### ISSUE TITLE
ASET IVA props have black outline

### ISSUE THREAD

**Issue by LGhassen** [LGhassen/Deferred#21]
https://imgur.com/a/Zht0xJW

**Comment by JonnyOThan** [comment]
Ah specifically it looks like it's the text renderer which would be using an alpha-blended texture and shader....shader source is here: https://github.com/FirstPersonKSP/RasterPropMonitor/tree/master/Shaders/Assets/Shaders

**Comment by LGhassen** [comment]
Created this PR to fix it https://github.com/FirstPersonKSP/RasterPropMonitor/pull/136
