### ISSUE TITLE
Water glitch when craft is near/in the water

### ISSUE THREAD

**Issue by DrPebber** [LGhassen/Deferred#27]
I made a new craft in a new save, launched it, opened a parachute at ~2000m, at around ~1000m or below some growing black patches appeared. When camera is moved to a place where patches weren't seen, they begin to appear and grow. When my craft landed camera went underwater for a sec and all the patches were gone for a minute, but then appeared and grew again.

I recently installed EVE, Scatterer, Spectra and Parallax, later TUFX. When I was installing TUFX in CKAN, Scatterer mod as well as configs were missing, I installed them back thinking that it was a reason of the issue, but it wasnt.

Here's a link for a log file since I cant load it here directly. Deleted the screenshots, but i can record a video if needed, thanks for amazing mods!

https://www.transfernow.net/dl/20240704xsuBk3Zm

My nickname on the KSP forum is Fanta_Racer is you need another point of contact.

**Comment by LGhassen** [comment]
This is caused by Scatterer and is unrelated to Deferred. I'm well aware of the issue but unable to reproduce it on my machines, seems machine-specific.

**Comment by DrPebber** [comment]
Oh, okay. Thanks for help.

**Comment by LGhassen** [comment]
Moved to scatterer https://github.com/LGhassen/Scatterer/issues/216
