### ISSUE TITLE
Bug: Terrain fails to load when Deferred is installed

### ISSUE THREAD

**Issue by TheRoyalRat** [LGhassen/Deferred#28]
This occurs only when deferred is installed. Have tried several combinations of enabled and disabled mods.

**Steps to reproduce:**

1. Install mod
2. Load savegame
3. Terrain is missing

**Screenshots:**
![ss2](https://github.com/LGhassen/Deferred/assets/43468859/eaeb6b8c-48a2-4980-be6e-2a88b1f19d60)
![ss1](https://github.com/LGhassen/Deferred/assets/43468859/4f64d4aa-b87e-4bb7-9dae-f6333440ba2d)

**Files in GameData folder:**
![ss3](https://github.com/LGhassen/Deferred/assets/43468859/497c962b-0ca4-4abe-a5ad-b8d07a6f1690)
_Note: V4 of the Fixed Volumetrics Deferred Rendering patch has been applied._

**List of mods:**
- Chatterer
- Community Tech Tree
- Easy Vessel Switch (EVS)
- Kerbal Attachment System (KAS) 
- Kerbal Engineer Redux
- Kerbal Inventory System (KIS)
- Kerbal Planetary Base Systems
- KSP Recall
- Mechjeb 2
- Parallax
- Restock
- Scatterer
- TUFX
- True volumetric clouds release 4
- Kopernicus
- Deferred

**Comment by LGhassen** [comment]
Update Parallax

**Comment by TheRoyalRat** [comment]
I am ashamed to say that you are right. Parallax' SpaceDock link leads to an older version. Thank you for providing assistance!

**Comment by LGhassen** [comment]
No need to be ashamed, glad to be of help!
