### ISSUE TITLE
Issues in RSS (and related mods)

### ISSUE THREAD

**Issue by Clayell** [LGhassen/Deferred#29]
The terrain fails to load in the editor scene.
![image](https://github.com/LGhassen/Deferred/assets/125416952/2e9d71e0-4882-477e-a5ab-9320e952bec2)

Something strange happens with the shadow details when moving the camera around in the editor.
![image](https://github.com/LGhassen/Deferred/assets/125416952/0baac1af-268c-438c-83d4-2fab8316894c)
![image](https://github.com/LGhassen/Deferred/assets/125416952/5dfc7bb8-7f53-4076-b878-a57a410d3d24)
![image](https://github.com/LGhassen/Deferred/assets/125416952/36b01575-43bc-43a2-8420-aa631d353be9)
![image](https://github.com/LGhassen/Deferred/assets/125416952/8df48f42-c079-4948-96aa-b1fffcf2853f)

The terrain is very shiny in the flight scene. (seems fine in the KSC scene as far as I can tell)
![image](https://github.com/LGhassen/Deferred/assets/125416952/33b6e569-ed65-42a0-9394-e63411174716)
![image](https://github.com/LGhassen/Deferred/assets/125416952/8a9771bb-4ace-45bc-92e7-676a370689c1)

Procedural Fairings turn white when the mouse is hovered near them, instead of the expected translucent. (this is probably the noted transparency issue)
https://youtu.be/BGDT3lRFajA

KSP.log:
https://drive.google.com/file/d/1bwIq-_UrPBlHx9xJ1oz3WuBvVBFn5qdO/view?usp=sharing

Installed mods:
> Actual Sites: Airports (ActualSitesAirports 1.0.1)
Advanced Jet Engine (AdvancedJetEngine v2.20.0)
AlphaMensae's Modular Launch Pads (ModularLaunchPads 2.7.0)
Approved Popular Pre-Launch Experiment (APPLE 1:1.1.9.1)
ASET Consolidated Agency (ASETAgency v2.0.2)
ASET Consolidated Avionics Pack (ASETAvionics v3.0.1)
ASET Consolidated Props Pack (ASETProps v2.0.7)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.6.1)
AutoRCS (AutoRCS 1.1)
B9 Aerospace Procedural Wings - Fork (B9-PWings-Fork 3:0.45.1)
B9 Part Switch (B9PartSwitch v2.20.0)
BahamutoD Animation Modules (BDAnimationModules 1:v0.6.7.1)
BetterBurnTime (BetterBurnTime 1.10)
BetterCrewAssignment (BetterCrewAssignment 1.4.1)
Camera Tools continued (CameraTools v1.34.0)
Chatterer (Chatterer 0.9.99)
Chatterer Extended (ChattererExtended 0.6.2)
ClickThrough Blocker (ClickThroughBlocker 1:2.1.10.21)
Community Category Kit (CommunityCategoryKit v112.0.1)
Community Resource Pack (CommunityResourcePack v112.0.1)
Conformal Decals (ConformalDecals 0.2.14)
Contract Configurator (ContractConfigurator v2.10.0.0)
Cryo Tanks (CryoTanks 1.6.5)
Cryo Tanks Core (CryoTanks-Core 1.6.5)
Cryogenic Engines (CryoEngines 1:2.0.6)
Custom Barn Kit (CustomBarnKit 1.1.22.0)
Custom Parachute Message (CustomParachuteMessage v1.0.1)
Custom Pre Launch Checks (CustomPreLaunchChecks 1.8.1.1)
DE_IVAExtension (DE-IVAExtension v1.2.0)
Debug Stuff (DebugStuff 1.7.0.0)
Deployable Engines Plugin (DeployableEngines 1.3.1)
Diazo's Landing Height Display (DiazosLandingHeight 2.3.0.1)
Distant Object Enhancement /L (DistantObject v2.1.1.16)
Distant Object Enhancement /L default config (DistantObject-default v2.1.1.16)
Docking Port Alignment Indicator (DockingPortAlignmentIndicator 6.10.0.0)
Dynamic Battery Storage (DynamicBatteryStorage 2:2.2.5.0)
Editor Extensions Redux (EditorExtensionsRedux 3.4.5)
Environmental Visual Enhancements Redux (EnvironmentalVisualEnhancements 3:1.11.7.2)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.1.2)
Filter Extensions - Default Configuration (FilterExtensionsDefaultConfig 3.2.9)
Filter Extensions - Plugin (FilterExtensions 3.2.9)
Firespitter Core (FirespitterCore v7.17)
Firespitter Resources config (FirespitterResourcesConfig v7.17)
FreeIva (FreeIva 0.2.18.4)
Hangar Extender (HangerExtenderExtended 3.6.0.2)
Harmony 2 (Harmony2 2.2.1.0)
Heat Control (HeatControl 0.6.1)
HullcamVDS Continued (HullcamVDSContinued 0.2.2.1)
Kerbal Alarm Clock (KerbalAlarmClock v3.14.0.0)
Kerbal Atomics (KerbalAtomics 1:1.3.3)
Kerbal Changelog (KerbalChangelog v1.4.2)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.9.0)
Kerbal Foundries2 (KerbalFoundriesContinued 2.4.8.18)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.7.5.0)
Kerbal Konstructs (KerbalKonstructs v1.8.7.0)
Kerbal Renamer (KerbalRenamer v1.7.0.0)
Kerbal Wind (KerbalWind 1:v1.0.2)
Kerbalism (Kerbalism 3.19)
Kerbalism - RealismOverhaul Config (Kerbalism-Config-RO v1.2.19.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.12.1-206)
KSA IVA Upgrade (KSAIVAUpgrade v1.6.7)
KSC Floodlights Mk2  (KSCFloodlightsMk2 1.0)
KSC Switcher (KSCSwitcher v2.1.0.0)
KSP Community Fixes (KSPCommunityFixes 1.35.2)
KSP Wheel (KSPWheel 1:0.16.14.33)
KSPBurst (KSPBurst v1.5.5.1)
Lunar Transfer Planner (LunarTransferPlanner v1.0.0)
MagiCore (MagiCore 1.4.0.0)
MechJeb 2 (MechJeb2 2.14.3.0)
Minimum Ambient Lighting Updated (MinAmbLightUpd 1.2.6.2)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.10.0)
Module Manager (ModuleManager 4.2.3)
ModuleDepthMask (DepthMask 1.1.3)
Navball Docking Alignment Indicator CE-2 (NavballDockAlignIndCE 1.1.1.3)
NavHud (NavHudRenewed 1.4.0.5)
Near Future Electrical (NearFutureElectrical 1.2.3)
Near Future Electrical Core (NearFutureElectrical-Core 1.2.3)
Near Future Exploration (NearFutureExploration 1.1.2)
Near Future Launch Vehicles (NearFutureLaunchVehicles 2.2.0)
Near Future Propulsion (NearFuturePropulsion 1.3.5)
Near Future Solar (NearFutureSolar 1.3.2)
Near Future Solar Core (NearFutureSolar-Core 1.3.2)
Parallax (Parallax 2.0.8)
Parallax - Stock Planet Textures (Parallax-StockTextures 2.0.8)
Parallax - Stock Scatter Textures (Parallax-StockScatterTextures 2.0.8)
Patch Manager (PatchManager 0.0.17.6)
Pood's Milky Way Skybox (PoodsMilkyWaySkybox v.1.3.0)
Precise Maneuver (PM) by Morse (PreciseManeuver 2:2.4.99.0-adoption)
Procedural Fairings (ProceduralFairings 1:v6.6.0.0)
Procedural Parts (ProceduralParts v2.5.9.0)
QuickGoTo (QuickGoTo 1:1.4.0.10)
QuickMute (QuickMute 1:1.4.0.8)
RasterPropMonitor (RasterPropMonitor 1:v0.31.13.4)
RasterPropMonitor Core (RasterPropMonitor-Core 1:v0.31.13.4)
RCS Build Aid (RCSBuildAid v1.0.6)
Real Antennas (RealAntennas v2.3.1)
Real Fuels (RealFuels 1:v15.9.0.0)
Real Plume (RealPlume 2:v13.3.2)
Real Solar System (RealSolarSystem v20.1.2.0)
Real Solar System Textures - 8192 x 4096 (RSSTextures8192 v18.6.1)
RealChute for Stock (RealChuteForStock v1.4.9.4)
RealChute Parachute Systems (RealChute v1.4.9.4)
RealHeat (RealHeat v5.1)
Realism Overhaul (RealismOverhaul v17.10.0.0)
Realistic Progression One (RP-1) (RP-1 v3.9.0.0)
Reentry Particle Effect Renewed (ReentryParticleEffect 1.9.1.1)
ReStock (ReStock 1.4.5)
ReStock Extra - Rigid Legs (RestockRigidLegs 1.4.5)
ReStock+ (ReStockPlus 1.4.5)
Retractable Lifting Surface Module (RetractableLiftingSurface 0.2.1.2)
Reviva (Reviva 1.0.0)
RO Capsules (ROCapsules v2.4.0.0)
RO Engines (ROEngines v2.9.0.0)
RO Heatshields (ROHeatshields v1.2.0.0)
RO Library (ROLib v1.9.1.0)
RO Solar (ROSolar v2.1.2.0)
RO Tanks (ROTanks v2.10.0.0)
ROEngines Extended (ROEnginesExtended 2.3.0)
ROLoadingImages (ROLoadingImages v1.0.0.0)
ROUtils (ROUtils v1.0.1.0)
RP-1 TechTree Kompacted (RP1TechTreeKompacted 1.3)
RSS CanaveralHD (RSS-CanaveralHD v1.0.1)
RSS DateTime Formatter (RSSDateTimeFormatter v1.12.1.0)
RSS Visual Enhancements - Low Resolution (RSSVE-LR 2.1.6)
Scatterer (Scatterer 3:v0.0876)
Scatterer Default Config (Scatterer-config 3:v0.0876)
Scatterer Sunflare (Scatterer-sunflare 3:v0.0876)
Shabby (Shabby 0.3.0.0)
Shaddy (Shaddy v2.5)
Show FPS (ShowFPS 1:0.3.1.3)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Solver Engines plugin (SolverEngines v3.14.0)
SpaceTux Library (SpaceTuxLibrary 0.0.8.6)
Staged Animation (StagedAnimation v2.0)
Superfluous Nodes (SuperfluousNodes 0.8)
SXTContinued (SXTContinued 2:0.3.29.9)
TAC Fuel Balancer (TacFuelBalancer v2.21.5.3)
Test Lite (TestLite 0.3.5)
TextureReplacer (TextureReplacer v4.5.3)
Textures Unlimited (TexturesUnlimited 1.5.10.25)
The Janitor's Closet (JanitorsCloset 0.3.8)
Time Control (TimeControl 1:2.11)
Toolbar Controller (ToolbarController 1:0.1.9.11)
TooManyOrbits (TooManyOrbits 1.1.6.6)
Transfer Window Planner - Fork (TransferWindowPlannerFork v1.9.1.0)
Trim Indicator (TrimIndicator 1.12.0.0)
TrimIndicators (TrimIndicators 0.1.0.4)
TUFX (TUFX 1.0.7.1)
TweakScale Redistributable (TweakScale-Redist v2.4.8.3)
VABReorienter (VABReorienter 1.2)
Ven's New Parts (VenStockRevamp-NewParts v1.16.0)
Ven's Stock Part Revamp Core (VenStockRevamp-Core v1.16.0)
Waterfall Core (Waterfall 0.9.0)
WaypointManager (WaypointManager 2.8.4.2)
Who Am I? (WhoAmI 1.4.0)

I would like to note that using deferred lighting instead of planetshine on RSS planets seems to work fine.

**Comment by Clayell** [comment]
Additional bug, the flight scene in the atmosphere shows strange black blobs of terrain, with seems to slightly correlate with the cloud position? Not sure. (using normal EVE clouds, not volumetric) The bug goes away when in the space flight scene.

https://youtu.be/7tTK-s5YfrY

**Comment by Clayell** [comment]
> Additional bug, the flight scene in the atmosphere shows strange black blobs of terrain, with seems to slightly correlate with the cloud position? Not sure. (using normal EVE clouds, not volumetric) The bug goes away when in the space flight scene.
> 
> https://youtu.be/7tTK-s5YfrY

This bug seems to be active or inactive depending on the tufx profile I use, I'll have to test which specific setting removes the bug.

**Comment by Clayell** [comment]
> This bug seems to be active or inactive depending on the tufx profile I use, I'll have to test which specific setting removes the bug.

Alright, so the black blobs directly correspond to the cloud position, and they also appear in the tracking station view. Additionally, it is definitely **HDR** that triggers this bug. When HDR is **on**, the bug appears, but when HDR is **off**, the bug vanishes. In the following pictures I have only changed the HDR setting.

![image](https://github.com/user-attachments/assets/628b8dbe-f80e-4606-bf9c-75c40ad2a2d9)
![image](https://github.com/user-attachments/assets/bb3caca8-1100-43c1-8aba-6eed68665e46)

**Comment by LGhassen** [comment]
@Clayell for the black cloud artifacts, this can be fixed by setting the _ShadowFactor value in the cloud config "EarthCloudsLow" to 0.75 or any other value below 1 (default is 3), can you confirm this works?

I'm looking into the other issues.

**Comment by Clayell** [comment]
> cloud config "EarthCloudsLow"
Where do I find this config?

**Comment by LGhassen** [comment]
In the EVE UI

**Comment by LGhassen** [comment]
I'll list procedurail fairings as incompatible and handle it separately. The other issues will be fixed in the next version apart from the shadows in the editor which is a stock issue I won't look into now.

**Comment by Clayell** [comment]
> @Clayell for the black cloud artifacts, this can be fixed by setting the _ShadowFactor value in the cloud config "EarthCloudsLow" to 0.75 or any other value below 1 (default is 3), can you confirm this works? This seems to be independent from deferred btw and just related to hdr and cloud shadows.

Yep, can confirm that setting the value below 1 removes the black cloud artifacts, thanks! Perhaps some sort of check should be put in place with EVE and/or TUFX to turn that value down if HDR is enabled?

**Comment by LGhassen** [comment]
I will just cap the end result to be between 0-1

**Comment by LGhassen** [comment]
The other issues should be fixed now in yesterday's version, apart from the shadows in the editor, and the hdr cloud shadow issue which will be fixed separately in the next EVE/Scatterer update. Feel free to reopen this if you see any issues.

**Comment by Clayell** [comment]
> The terrain fails to load in the editor scene.
> The terrain is very shiny in the flight scene. (seems fine in the KSC scene as far as I can tell)

Confirmed fixed.

**Comment by Clayell** [comment]
Interestingly, the transparency stuff seems to depend on the TUFX profile. Using Default-Editor/Empty gives the normal white opaque stuff, but using Default-MainMenu/KSC/Tracking/Flight fixes the bug entirely.
Looking into the TUFX settings, it seems to be another bug entirely controlled by HDR. (where turning HDR on fixes it) Might be worth looking into.

Default-Editor
![image](https://github.com/user-attachments/assets/dc2ac7f1-f889-471e-a61f-b0f816492698)

Default-Editor with HDR on
![image](https://github.com/user-attachments/assets/fd1dfc11-1b91-4985-ba23-e77d887922b3)

(although it seems that the transparency in the fairing only shows radially attached parts? might be a stock bug idk)

**Comment by Clayell** [comment]
@LGhassen I think you force-closed this issue or something, I can't re-open it.

**Comment by LGhassen** [comment]
Not RSS related, I listed procedural fairings as incompatible in the compat list

**Comment by Clayell** [comment]
> Not RSS related, I listed procedural fairings as incompatible in the compat list


Yes, but I think you should mention that turning HDR on removes the "white fairing" issue with procedural fairings.

**Comment by Clayell** [comment]
I think the offending module is "ModuleSeeThroughObject", which is used in Procedural fairings for the "invisible fairings when hovering over them" feature, as well as in [several other RO repos](https://github.com/search?q=org%3AKSP-RO+ModuleSeeThroughObject&type=code&p=1).

**Comment by techdragon** [comment]
Does this open up a potential fix? Anyone tried to patch out the use of the offending module yet?

**Comment by Clayell** [comment]
ModuleSeeThroughObject is a stock module (although not used in stock I think), so I think compatibility is better than declaring it to be entirely invalid. It is noted in the readme that normal stock fairings get a [special effect](https://github.com/LGhassen/Deferred#transparency) applied, so if that effect could be applied to ModuleSeeThroughObject as well, I think this would be considered fixed.

**Comment by Clayell** [comment]
<img width="1449" height="139" alt="Image" src="https://github.com/user-attachments/assets/506e4245-2ddd-4830-a6fd-cbea5b2f8d72" />

Oh actually it is used in stock in two deprecated parts, `ServiceBay_125` and `ServiceBay_250`. We should expect to see the same bug on those parts too.

Would probably have to load into a verison before 1.2 (I think it was deprecated in this version?) to even load these parts correctly though...

<img width="984" height="299" alt="Image" src="https://github.com/user-attachments/assets/04d52d43-bc40-4b9c-9f99-d3fe4f5ed9ae" />

**Comment by Clayell** [comment]
To compare how they set opacity:
`ModuleSeeThroughObject`:
```
public void SetOpacity(float o)
{
	opacity = o;
	int num = mrs.Length;
	while (num-- > 0)
	{
		mrs[num].material.SetFloat(PropertyIDs._Opacity, o);
	}
}
```

---

`ModuleProceduralFairing` (uses `FairingPanel.SetOpacity`):
```
public void SetOpacity(float o)
{
	opacity = o;
	if (mpb == null)
	{
		mpb = new MaterialPropertyBlock();
	}
	mpb.SetFloat(PropertyIDs._Opacity, o);
	mr.SetPropertyBlock(mpb);
	if (attachedFlagParts == null)
	{
		return;
	}
	for (int i = 0; i < attachedFlagParts.Count; i++)
	{
		for (int j = 0; j < attachedFlagParts[i].flagMeshRenderers.Count; j++)
		{
			attachedFlagParts[i].flagMeshRenderers[j].SetPropertyBlock(mpb);
		}
	}
}
```

---

So ModuleSeeThroughObject sets a value in `MeshRenderer.Material`, while ModuleProceduralFairing defines a `MaterialPropertyBlock` and sets the `MeshRenderer` to use that property block.
