### ISSUE TITLE
terrein has weird effect.

### ISSUE THREAD

**Issue by Vuscin** [LGhassen/Deferred#3]
Hello! i installed all the mods related to this post and now I have a problem. it is showing a circle of black particles around my vessel, and only when zoomed in. 
![image](https://github.com/LGhassen/Deferred/assets/165175858/3373a834-dced-4e25-a4b6-490287b729c4)

**Comment by LGhassen** [comment]
As it says in the Patreon post and the compatibility list, Parallax is not compatible yet.

**Comment by Vuscin** [comment]
![image](https://github.com/LGhassen/Deferred/assets/165175858/889ecc97-09be-4b50-b1f5-e9047504da49)

**Comment by Vuscin** [comment]
> As it says in the Patreon post and the compatibility list, Parallax is not compatible yet.

thank you for you're help, and thank you for this work of yours. thanks.
