### ISSUE TITLE
Csouds dissapear when using v4 fix

### ISSUE THREAD

**Issue by BryanAM7** [LGhassen/Deferred#31]
If I don't use the fix all works good but the droplets on the windows when rains move backward,
![Ksp droplets bug](https://github.com/LGhassen/Deferred/assets/38803358/bc0dbca8-5631-463b-badc-73869b56349d)
 and if I use the fix, the droplets get fixed, but volumetric clouds stops working
im using EarlyAccess22_12_23
there is anyway i can just use the droplets fix from v4 fix?  ty

**Comment by LGhassen** [comment]
Send me a message on Patreon I'll just send you the newest version with the built-in fixes.
