### ISSUE TITLE
TU compatiblity fork and fairings

### ISSUE THREAD

**Issue by Fawkes511** [LGhassen/Deferred#32]
First of all thank you for your amazing work. I apologize in advance if this is the wrong way to communicate this issue... but I couldn't find another.

I have found that the current TU compatibility fork breaks the fairings when using TURD, forcing white color regardless of stock variant selection (orange, etc) and disabling the recoloring features completely. **I am aware that fairings are listed as not working properly on TURD's forum page**, so I understand if there is no reason to bother with this, however, I had them working properly, and I have tested and verified that it is the compatibility fork that causes this issue.

I believe the reason for this is the Transparency effects changes that Deferred introduces . I do not know nearly enough about any of this to be sure, but I imagine a proper fix would probably require work from whoever is behind TURD, and in any case I understand that getting these two things to work together is not anyone's priority.

That said, in the current state this forces a choice between TU-Deferred compatibility and working fairings, which is a shame. I humbly request if it were at all possible to make a version of the compatibility fork that excludes fairings from Deferred completely, such that they "Render in Forward" as it is called on the main page.

**Comment by LGhassen** [comment]
Include screenshots of the affected fairings and how to reproduce the issue, I have no idea which TURD fairings those are

**Comment by LGhassen** [comment]
Thanks for the detailed report, I'll check this

**Comment by LGhassen** [comment]
@Fawkes511 It seems that TURD has and supplies its own fork of TU which is what enables the fairing recoloring. My compatibility fork is based on the original TU which doesn't have this functionality.

Without having deferred installed, using original TU breaks fairing recoloring, while using TURD's TU allows it to work. All I need to do is integrate the changes from TURD's TU fork.

Do you know anything about where the source of this fork is? I only looked briefly but couldn't locate the source code for it, maybe its linked somewhere in the forum thread.

**Comment by Fawkes511** [comment]
Not sure if this is what we're looking for but it seemed possible https://bitbucket.org/net-lisias-ksp/turd/src/master/Source/Stock_Recolour/

**Comment by LGhassen** [comment]
That's the compiled fork but not the source, I'll dig around

**Comment by Fawkes511** [comment]
Agh, I feeared as much. Sorry I couldn't find better. User "Manwith Noname" Seems to be in charge of TURD in [the forum page](https://forum.kerbalspaceprogram.com/topic/174188-112x-textures-unlimited-recolour-depot/), maybe I could try asking him about it.

**Comment by LGhassen** [comment]
I've already messaged him, he seems active.

**Comment by LGhassen** [comment]
@Fawkes511 according to Manwith Noname, only the .dll (not the shaders) are different and they are pulled from the dev branch of TU. Therefore if you do the following it should work:

- Download the version of TU bundled with TURD
- Replace only the 000_TexturesUnlimited\Shaders folder with the Shaders folder from my fork

I haven't tested it but it should work. If it works I will make it the default thing.

**Comment by Fawkes511** [comment]
I just tested it and it works!!

Debug menu shows deferred is able to act as shown in situation 2, but I can swap between fairing variants, both stock and TURD as shown in situation 1 and everything works! Sporadically the white fairing will show up black after switching to other variants and then back to it,  but all it takes is to delete and rebuild the fairing and white with dissolve effect is back. Everything is pretty much working together almost flawlessly this way.

Thank you thank you thank you. You're a legend.

**Comment by LGhassen** [comment]
No problem. Thank you for testing it. I will roll these changes into my fork and call it a day for now :)

**Comment by LGhassen** [comment]
I updated my fork and the dev branch to include the changes.

**Comment by StringLP929** [comment]
Cant find it nowhere, can you show me How?

**Comment by LGhassen** [comment]
> I can't find it anywhere

Come on man

https://github.com/LGhassen/Deferred/?tab=readme-ov-file#mod-compatibility-status
