### ISSUE TITLE
Terrain does not load in a close range of any celestial body

### ISSUE THREAD

**Issue by MagicBoss812** [LGhassen/Deferred#33]
Every Planet besides Kerbin has this issue. After a very close altitude it makes the ground invisible and I can see the cosmic skybox and on some planets the atmosphere "glow" but without terrain.

**Comment by LGhassen** [comment]
As said in the readme "To report an issue add screenshots of the issue, reproduction steps and your KSP.log file, otherwise your report may not be taken into account". Reopen this issue if you add all the necessary info.
