### ISSUE TITLE
Flags on parts seem to render in forward

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [LGhassen/Deferred#35]

**Comment by LGhassen** [comment]
Flags are a transparency, they will always render in forward for that reason. Their shader is also all kinds of fucked so I will not go through the trouble of recreating it just to add ambient.

CineboxAndrew is working on full deferred support for ConformalDecals. Use ConformalDecals instead. Flags are a garbage feature.

**Comment by CosmicDreamsOfCode** [comment]
Gotcha!

**Comment by J-Ray17** [comment]
Was the project for compatibility by CineboxAndrew still in the works?
