### ISSUE TITLE
The Mun is unusually shiny

### ISSUE THREAD

**Issue by Westbrooke117** [LGhassen/Deferred#37]
![image](https://github.com/user-attachments/assets/a7f69007-0a9a-41ee-b24c-25d87bf23200)
I don't believe the Mun is usually this reflective

**Comment by LGhassen** [comment]
I already commented on this on Reddit

> Deferred doesn't inherently make surfaces shiny or anything (e.g stock terrain looks about exactly the same, most existing parts keep their "spirit" and aren't made shiny), in this case that's the conversion Parallax does between its custom shading model and the standard shading model that is a bit shiny. Linx will probably fine tune these in the upcoming rewrite.
