### ISSUE TITLE
Some windows are just whited out in IVA

### ISSUE THREAD

**Issue by rascalnag** [LGhassen/Deferred#42]
Some windows (or material near windows) are just totally white. Tested on fresh install.

![image](https://github.com/user-attachments/assets/e1af5792-7269-4a8e-b34a-63b0351df783)

Example is of Mk1-3 but it also appears on the Mk1 pod's window.

Can't find much mention of this anywhere on discord or reddit. I am using an AMD card (6950XT), up to date on drivers. If developed on Nvidia and if most players have Nvidia (or if also AMD, not RDNA2), maybe there's a hardware specific thing going on. 

Steps to reproduce:

1. Install fresh KSP (or not fresh. Observed initially after installing plenty of mods).
2. Have an AMD card? RDNA2?
3. Enter Mk1 or Mk1-3 pod and look up at windows.

Planning to refine this. I have a 1660ti I can test with to confirm if it's AMD specific (just not today or tomorrow... slammed).

Another note. In debug mode, the offending materials are all white in emission, and all black in every other debug mode:

![image](https://github.com/user-attachments/assets/74e8d84c-9a2c-453d-bc95-9185973d2d39)
![image](https://github.com/user-attachments/assets/b9f1fa04-f1df-47e9-8dc8-284e487ddb36)
![image](https://github.com/user-attachments/assets/899e7ab7-c59c-4376-82f2-93c8d7fa2a69)

Log: 
[KSP.log](https://github.com/user-attachments/files/16632421/KSP.log)

**Comment by LGhassen** [comment]
This is indeed not reproducible on my machine with a clean install or otherwise (nvidia 2080 super), let me know if it doesn't happen with the 1660 ti.
I saw no issues in the log as well (thanks for testing it on a minimal install btw).

**Comment by rascalnag** [comment]
It still happens, which I guess is good news in that it's not a vendor thing but bad news in that I don't know what to try next! Hmmm... I'm trying to think if there's any wayward bits of KSP anywhere that might be harder to get to and clear. Something cached somewhere? Or maybe something with unity? Really funky. I will keep digging. Unity shenanigans strike me as plausible given the fresh KSP install...

**Comment by HarlanWang** [comment]
I encountered the same issue when installing deferred and mk1-2 iva replaced by aset.Only installing dependencies such as Harmony2 will not result in such a situation

**Comment by LGhassen** [comment]
@HarlanWang he's not using any of that

**Comment by rascalnag** [comment]
What’s interesting is I _used_ to have ASET, but yeah, this is all fresh now. I’ll try deleting stuff in squad and have steam verify it back maybe? Not sure why it would still be sticky.

**Comment by LGhassen** [comment]
I will give the 'MK1-2' IVA Replacement by ASET mod a test

**Comment by rascalnag** [comment]
Did another fresh install and went with manual installation over CKAN. Still no luck. I've also tried compiling the shaders myself, which also did not work. Tried deleting and verifying squad files. Tried -force-opengl, -force-glcore, -force-d3d12/11, same result. 

Is it apparent what the misbehaving shader in question is? If so I can try to tinker with things and experiment.

**Comment by LGhassen** [comment]
> Is it apparent what the misbehaving shader in question is? If so I can try to tinker with things and experiment.

No, unless you take a renderdoc capture and send it

**Comment by rascalnag** [comment]
Okay, I’ll try renderdoc tonight or tomorrow. Hopefully things finally become clearer.

**Comment by LGhassen** [comment]
I've installed the mk1-2 iva replacement with ASET and I'm not getting this issue

![image](https://github.com/user-attachments/assets/2b69a2c2-aac9-464c-877d-441c8854891c)

**Comment by rascalnag** [comment]
I just had the general ASET packs (which may include that) but overall yeah, not sure it’ll be reproducible. I should be able to get some time late tonight to use renderdoc… fingers crossed something pops up to diagnose this. It’s _probably_ on my end somehow but I haven’t the slightest idea what it could be.

Another thing I could maybe try is using my Ubuntu partition. That should fully isolate me from any weird sticky issues that might be causing this. If that works, maybe my windows installation just needs to get slapped around a bit…

**Comment by rascalnag** [comment]
![image](https://github.com/user-attachments/assets/00bed23d-71dd-48ca-9792-9491e147ac1b)

Captured this pixel history in renderdoc. looks like the colors are correct until that final pass, then it's just all white. This capture, plus another from the mk1 pod, linked below. Going to try to install ksp and deferred in ubuntu now...

https://drive.google.com/file/d/1EDm__guLyxZkdCE_LbQZC2vQIRYn7IeY/view?usp=drive_link

**Comment by rascalnag** [comment]
The problem followed me to Ubuntu... now I'm really at a loss. Should be totally clean there. I mean... could it be a CPU thing (5800x3D)? Just trying to isolate some sort of common factor...

**Comment by LGhassen** [comment]
Ok I got this to happen today. If you install tufx and enable hdr (or use any profile with hdr enabled) it fixes it. I'm looking into it.

**Comment by rascalnag** [comment]
No problem, glad to provide info. And that’s good to hear! I will be able to verify that fix after work. Fingers crossed. If there’s anything I can test or do to make tracking down why that happens in the first place easier just let me know.

**Comment by LGhassen** [comment]
I think this should fix it (both with and without HDR), https://drive.google.com/file/d/1lK7qUlanT7praEztntzdVBnpvjJCfg0M/view?usp=sharing

Can you test it? I haven't tested in depth. Also if you can just play with it for a while as you normally play and watch out for any issues

**Comment by rascalnag** [comment]
Awesome, and will do! I’ll run a few missions tonight on a basic install and check the windows a bunch throughout.

**Comment by rascalnag** [comment]
Windows are fixed! Though I have noticed some lighting differences overall:

Old:
![image](https://github.com/user-attachments/assets/addbafac-6faa-4586-95aa-ba60499f4d26)

New: 
![image](https://github.com/user-attachments/assets/550d8cd3-51d1-46de-bcc5-d4f50d1bef2d)

But it doesn't really look broken. In fact I think the old version was actually looking a bit off. It might have just been something bugged related to this issue that I did not notice until this comparison. Tinkering with the cfg's ambient settings helped tone it down a little. I assume this is something that also will change when I install more graphical mods and TUFX and the output is tweaked accordingly.

Lastly, I do notice this flickering when around low orbit (or just zooming the camera out to around this height and moving it around):

https://streamable.com/ho3rro

But I went back and found the released version also appears to do it. So not an effect of this fix. If you're familiar with it, I'd be curious if there are any mitigations. But overall, that's another issue...

Anyway, thank you very much for all the time spent fixing this! I did not expect it to become such a rabbit hole. Very glad to be able to see out of windows again. If you don't notice anything concerning with the lighting change, probably can be closed!

**Comment by LGhassen** [comment]
There were other changes, small fixes to the normals around KSC, fixes to the color space conversion, which might affect the colors a bit. It shouldn't be too noticeable of a difference but if you say it looks better then that's fine.

Concerning the other issue, that's around the transition from local to scaled space (160 km) which the stock ocean doesn't handle well in deferred (and which I'm not going to bother fixing). If you use scatterer then everything will work correctly  and you won't get that pop.

Thanks a lot for testing it. I consider this fixed but will only release publicly in a few days just to have a bit more time to play with it and make sure there no hidden issues.

**Comment by LGhassen** [comment]
@rascalnag I've actually updated the fix because I noticed some issues with that version with mods that use depthMasks like restock. Should be much more robust now: https://drive.google.com/file/d/1yuAuMGA7pe6vt8CUbOzzu5w4EJ7o7MGP/view?usp=sharing

**Comment by rascalnag** [comment]
Okay, that explanation makes sense. I’ll give the updated version a go tonight, thank you!

**Comment by rascalnag** [comment]
All looked good! Also loaded up a heavier modset including TUFX, Scatterer, Volumetrics, Parallax, and Restock. Found nothing wrong.

**Comment by LGhassen** [comment]
This is publicly released now
