### ISSUE TITLE
Heat/atmospheric effects pass through fairings.

### ISSUE THREAD

**Issue by wepav1** [LGhassen/Deferred#45]
Screenshots taken in a clean install with deferred, scatterer and module manager. Seems to happen when fairings are close to the parts inside.

![base](https://github.com/user-attachments/assets/f82cc714-b720-4d34-8582-9c28b7eb4420)
![base2](https://github.com/user-attachments/assets/354a56e2-f8de-4fc6-b986-0a836527baa5)
Doesn't happen in oversized fairings.

album with debug screenshots and log:
https://photos.app.goo.gl/SBjSXhCEfk9H1oKM9

[KSP.log](https://github.com/user-attachments/files/17301553/KSP.log)

**Comment by LGhassen** [comment]
I'm not sure what the issue is supposed to be looking at the screenshots. Can you include comparisons with stock or a better explanation of the issue?

**Comment by wepav1** [comment]
It seems that with deferred aerodynamic effects are interacting with what is inside the shell instead of the outer shell. I think it's only visual because parts inside don't get heat and the debug doesn't show any drag.

deferred
![Screenshot (35)](https://github.com/user-attachments/assets/b6074e21-3e98-407b-aea2-210def84571a)
vanilla
![Screenshot (38)](https://github.com/user-attachments/assets/8ed5598a-c2e0-47f9-8707-0851bc15ab54)
deferred
![Screenshot (34)](https://github.com/user-attachments/assets/06830f58-f469-4da5-8e28-067c7ae955c9)
vanilla
![Screenshot (37)](https://github.com/user-attachments/assets/3c025fb0-61f2-447b-bec9-876c9d24a757)
deferred
![Screenshot (31)](https://github.com/user-attachments/assets/1af54b67-9d57-4780-aefa-b0f2ec8fe6e6)
vanilla
![Screenshot (32)](https://github.com/user-attachments/assets/88c5fd5f-8a7e-46d6-afdd-03e6d9296b72)

**Comment by LGhassen** [comment]
I will check it, thanks for the comparisons!
