### ISSUE TITLE
Pacific Ocean Blank Space in Flight Scene

### ISSUE THREAD

**Issue by njd80** [LGhassen/Deferred#49]
There is a blank space where clouds and detail are missing over the Pacific ocean. Only in the flight scene - Map view shows the clouds correctly. Seen with all craft in the same place.

This is a new install of Deferred via CKAN added on top of an existing RO/RSS/RP-1 installation.

![screenshot109](https://github.com/user-attachments/assets/d1b39049-5a93-449d-80b8-f2eda4c7edbf)
![screenshot110b](https://github.com/user-attachments/assets/7d2e73cd-0ec4-4e0f-8a34-b8ffb0ff8b48)

**Comment by LGhassen** [comment]
1. Include KSP.log file please
2. Is scatterer ocean enabled?
3. I don't know if RO/RSS/RP-1 uses any custom terrain shaders or anything like that

**Comment by njd80** [comment]
Reinstalled to get those bits of information for you and now cannot reproduce it. It looks good now
Sorry to have wasted your time
