### ISSUE TITLE
(Initial) EVA headlamps temporarily wink out when using MMU

### ISSUE THREAD

**Issue by 68-RPM** [LGhassen/Deferred#5]
Playing with the Initial Release build the other day, I observed that the EVA headlamp would momentarily shut off when inputs were given to the jetpack. A brief additional test with only Squad and SquadExpansion installed failed to replicate it, confirming the issue's source.
Only these mods were installed (IIRC)

- Deferred
- TUFX
- Volumetric Clouds (Early-access EVE Redux & Scatterer)
- ReStock
- ReStock Plus

This feels like the sort of thing that would be silently fixed, but I didn't see it explicitly mentioned in the more recent release notes from this morning. Logs are unavailable as they were overwritten a short while later.

https://github.com/LGhassen/Deferred/assets/173549460/91ac8493-a812-4f90-a0b6-b9f088b38940

**Comment by LGhassen** [comment]
I have no idea how this could happen

**Comment by LGhassen** [comment]
This seems to be due to the stencil values used on parts, that bit may also be reserved by unity lights. I will review stencil usage.
