### ISSUE TITLE
Failure in subsystem : Internal props compilation

### ISSUE THREAD

**Issue by Nymbat-The-Eternal** [LGhassen/Deferred#6]
Hi. I installed the latest update and my game is now refusing to load. It always crashes when trying to load Prop: Squad/Props/PropsGeneric/Seat_Pilot/Seat_Pilot
The following is the error message it gives me while loading: 
Loading has failed due to an unhandled error

Failure in subsystem : Internal props compilation
Prop: Squad/Props/PropsGeneric/Seat_Pilot/Seat_Pilot

System.NullReferenceException: Object reference not set to an instance of an object
  at PartLoader.ReplaceTextures (UnityEngine.GameObject model, System.Collections.Generic.List`1[T] textureNames, System.Collections.Generic.List`1[T] newTextures) [0x00247] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at PartLoader.CompileModel (UrlDir+UrlConfig cfg, ConfigNode partCfg, System.Single scaleFactor, AvailablePart partInfo) [0x004d4] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at PartLoader.LoadInternalProp (UrlDir+UrlConfig urlConf) [0x00053] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at PartLoader+<CompileInternalProps>d__75.MoveNext () [0x000c3] in <4b449f2841f84227adfaad3149c8fdba>:0 
  at KSPCommunityFixes.Performance.KSPCFFastLoader+<FrameUnlockedCoroutine>d__63.MoveNext () [0x00146] in <d08a67791ddc409fad78e1e6485c71dc>:0 
  
  The following is the contents of my GameData folder: 
000_ClickThroughBlocker
000_Harmony
000_NiakoUtils
000_TexturesUnlimited
000_Toolbar
001_ToolbarControl
AllYAll
Apex
ASET
Astrogator
AtmosphereAutopilot
AutoAGL
AutoAsparagus
AvaliSpaceProgram
B9PartSwitch
B9_Aerospace_ProceduralWings
Benjee10_sharedAssets
Benjee10_stowaway
BetterRocketDesigns
CommunityResourcePack
ContinuousCollisions
ContractConfigurator
CorrectCOL
CustomPreLaunchChecks
DecouplerShroud
Deferred
DE_IVAExtension
DiffuseR
EasyBoard
EasyVesselSwitch
EditorExtensionsRedux
EnvironmentalVisualEnhancements
EvenMoarActionables
ExtraplanetaryLaunchpads
FieldTrainingFacility
FillItUp
Firespitter
ForScience
FreeIva
FreeLaunchClamps
FuelMyShip
GRAPEFRUIT
GravityTurn
GroundEffect
HabTechProps
HideEmptyTechTreeNodes
HUDReplacer
Interkosmos
IVA_Patches
JoolBiomes
JSI
kAerospace
KcalbelohSystem
KEI
KerbalEngineer
KerbalJointReinforcement
KerbalKonstructs
KerbalStats
KerbalVR
KerbealisticDocking
KerboKatz
KerbthulhuKineticsProgram
KesslerSyndrome
KGEx
Kopernicus
KopernicusExpansion
Kronometer
KSA
KSCExtended
KSCHarbor
KspBugReport
KSPCommunityFixes
KSPIRC
KSTS
LadderWarp
LagrangeProyect
LazyPainter
M-ISPx2
MechJeb2
MechJebForAll
MiningExpansion
Mk3Expansion
Mkerb
MoarActionables
ModularFlightIntegrator
NavyFish
NearFutureProps
NightShift
NotSoSimpleConstruction
Nymbat
OSSNTR
ParallaxR
PartCommanderContinued
PatchManager
PersistentRotation
PhysicsHold
PlanetShine
ProbeControlRoom
ProceduralFairings
QuickBASIC
QuickMods
RationalResourcesParts
RCSBuildAid
RealisticAtmospheres
Rescale 10.618x
RetractableLiftingSurface
Reviva
RocketSoundEnhancement
RocketSoundEnhancementDefault
SCANsat
Shabby
Shaddy
Sigma
SigmaDimensions
SimpleConstruction
SimpleLogistics
Singularity
SmartParts
SmartStage
SmokeScreen
SpaceTuxLibrary
SpaceY
Spectra
Stock folder: Squad

Stock folder: SquadExpansion

StageRecovery
StationScience
SurfaceLights
SushutsMainMenu
SXT
TeaKettleRCS
TextureReplacer
ThroughTheEyes
Trajectories
TriggerTech
TSSafetyNet
TundraSpaceCenter
TURD
TweakScale
UJModlets
VariantPersist
VesselView
VRAMr
WarpEverywhere
WhereCanIGo
ZTheme
zzz_Deferred
999_Scale_Redist.dll
999_Scale_Redist.version
DockingPortExtendedRotation.cfg
ModuleManager.4.2.3.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
MultiStarSolarPanels.cfg
RS-25 SSME.cfg
S.A.V.E.dat
toolbar-settings.dat
VR_human_hands.cfg

  Removed duplicate Deferred folder.
Removed KSP Community Fixes.
Loading hangs at Squad/Props/PropsGeneric/Seat_Pilot/Seat_Pilot

**Comment by Nymbat-The-Eternal** [comment]
Removed duplicate Deferred folder. 
Removed KSP Community Fixes.
Loading hangs at Squad/Props/PropsGeneric/Seat_Pilot/Seat_Pilot

**Comment by LGhassen** [comment]
Try to narrow it down and find the exact part mod that causes a conflict with Deferred, because that list is too big.

**Comment by Nymbat-The-Eternal** [comment]
Holy Kraken. I got a hole in one. I removed Kerbal VR and it loaded right up. Guess I better go let JonnyOThan know.

**Comment by LGhassen** [comment]
lol nice one, I'll talk to jonny directly, this is similar to another issue I ran into.

**Comment by LGhassen** [comment]
It's fixed now, get the latest release.

Let me know if this actually works in VR.

**Comment by Nymbat-The-Eternal** [comment]
It works perfectly in VR.

**Comment by LGhassen** [comment]
Thanks a lot for confirming
