### ISSUE TITLE
B9 Proc Wings mostly render in forward

### ISSUE THREAD

**Issue by afyber** [LGhassen/Deferred#8]
What the title says, B9 Procedural Wings currently render as in vanilla KSP, EXCEPT for the wing "ends", which render with deferred and show up in debug mode (unlike the rest of the wings), I've attached multiple screenshots showing an example, you can see that the tops of the tails are visible in the debug screenshots.
![screenshot1](https://github.com/LGhassen/Deferred/assets/26539285/296bca5b-7ec8-447f-89b4-e21c47f3b848)
![screenshot2](https://github.com/LGhassen/Deferred/assets/26539285/71d2ed6b-87a2-4c14-8977-4328001abd5a)
![screenshot3](https://github.com/LGhassen/Deferred/assets/26539285/d2f24d87-b188-4835-adb2-5f47c6c2ffb2)

**Comment by LGhassen** [comment]
Thanks a lot for using the debug menu and providing screenshots. I will look into it.

**Comment by LGhassen** [comment]
I opened a [pull request](https://github.com/B9-Procedural-Wings/B9-PWings-Modified/pull/27) to proc wings to fix this. Feel free to try [my version](https://github.com/LGhassen/B9-PWings-Modified/releases/tag/deferred) or wait for an official new version.
