### ISSUE TITLE
Craft looks lit while terrain/water is completely dark at night on Kerbin

### ISSUE THREAD

**Issue by Turbo49** [LGhassen/Deferred#9]
![220200_185](https://github.com/LGhassen/Deferred/assets/121303343/e0b9d508-3567-4271-bbda-24eaa70c81b5)
I don't know if it's intended, but here the lighting looks pretty unnatural to me. Is it the sky that's reflecting on the craft ?

Mod list if needed:
![image](https://github.com/LGhassen/Deferred/assets/121303343/657c9a93-078b-4790-8431-188924c8ecef)

**Comment by LGhassen** [comment]
That's the flat ambient which already exists in the base game. I chose to keep it for gameplay reasons. If you wanna disable look into the ambient light mod it probably offers a way to disable it.
